replicaCount: 1

image:
  repository: n01717500/gitops-webapp
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 5000

mysql:
  rootPassword: rootpassword
  database: itemsdb
  user: root
  password: rootpassword
serviceAccount:
  create: true
  name: ""
ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []
