apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gitops-webapp-chart.fullname" . }}
  labels:
    {{- include "gitops-webapp-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gitops-webapp-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gitops-webapp-chart.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gitops-webapp-chart.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            # add env vars if needed, or remove this block if none
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
