name: CI - Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: n01717500/gitops-webapp:latest

      - name: Update Helm Chart image tag
        run: |
          sed -i "s/tag: .*/tag: latest/" gitops-webapp-chart/values.yaml
          git config --global user.name "Harshil Rao"
          git config --global user.email "harshilrao@example.com"
          git add gitops-webapp-chart/values.yaml
          git commit -m "Update Helm chart image tag to latest"
          git push
